name: to operate functions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  job1:
     name: addition
     runs-on : ubuntu-latest
     steps:
       - shell : bash
         run: |
           expr 2+4 > Addbook.txt
      
       - name: upload AddResult for job1
         uses: actions/upload-artifact@v2
         with :
           name : Book1
           path: AddBook.txt

  job2:
     name : substract
     needs : job1
     runs-on : ubuntu-latest
     steps:
       - name : download add result for job1
         uses : actions/download-artifact@v2
         with :
           name: Book1
       - shell: bash
         run: |
           value='cat AddBook.txt'
           expr $value -3 >AddBook.txt
           echo substraction is $value
       -  name: upload results for job2
          uses: actions//upload-artifact@v2
          with:
            name: Book1
            path: Addbook.txt

